# Generated by Django 3.2.6 on 2021-08-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('teext_area', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(choices=[(0, 'in progress'), (1, 'complete')], default=0)),
            ],
        ),
    ]
