# Generated by Django 3.2.6 on 2021-08-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='teext_area',
            new_name='text_area',
        ),
    ]
